name: aimg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - tkinter
    - pillow
    - requests
    - numpy
    - pytest
    - pytest-cov
    - black
    - flake8
    - mypy
    - python-dotenv
    - fastapi
    - uvicorn
    - sqlalchemy
    - pydantic
    - python-multipart
    - aiofiles
    - jinja2
    - httpx
    - websockets
    - opencv-python
    - scikit-image
    - torch
    - torchvision
    - transformers
    - diffusers
    - accelerate
    - safetensors
    - tqdm
    - rich
    - typer
    - click
    - pyyaml
    - jsonschema
    - python-jose[cryptography]
    - passlib[bcrypt]
    - python-multipart
    - aiofiles
    - jinja2
    - httpx
    - websockets
    - opencv-python
    - scikit-image
    - torch
    - torchvision
    - transformers
    - diffusers
    - accelerate
    - safetensors
    - tqdm
    - rich
    - typer
    - click
    - pyyaml
    - jsonschema
    - python-jose[cryptography]
    - passlib[bcrypt] 